#!/bin/bash
#PBS -l nodes=n21:ppn=2
#PBS -N Unet
#PBS -m e
#PBS -l walltime=48:00:00
cd $PBS_O_WORKDIR
cd ~/CompVision/project_5_neural_style_transfer/
module load python cuda
python3 neural_style_transfer.py > output.txt
